# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jokoa', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retro_IPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=150, verbose_name=b'Izena')),
                ('status', models.CharField(choices=[(b'0', b'Erdizka'), (b'1', b'Probatzeko'), (b'2', b'Amaituta')], default=b'0', max_length=1, verbose_name=b'Egoera')),
                ('ipsfile', models.FileField(upload_to=b'ips')),
                ('publikoa_da', models.BooleanField(default=False, verbose_name=b'Publikoa da')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'publikazio data')),
                ('mod_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'modifikazio data')),
                ('jokoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokoa.Jokoa')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokoa.Plataforma')),
            ],
            options={
                'verbose_name': 'Retro IPS file',
                'verbose_name_plural': 'Retro IPS files',
            },
        ),
    ]
