# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('jokoen_itzulpenak', '0003_euskarazkojokoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Euskalinkak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=150, verbose_name=b'Izena')),
                ('url', models.URLField()),
                ('publikoa_da', models.BooleanField(default=False, verbose_name=b'Publikoa da')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'publikazio data')),
                ('irudia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
            ],
            options={
                'verbose_name': 'Euskal lotura',
                'verbose_name_plural': 'Euskal loturak',
            },
        ),
    ]
