# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokoen_itzulpenak', '0004_euskalinkak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euskalinkak',
            name='irudia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
    ]
