# Generated by Django 2.2.17 on 2020-12-21 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Izenburua')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hasiera data/ordua')),
                ('end_date', models.DateTimeField(default=None, null=True, verbose_name='Amaiera data/ordua')),
                ('twitch_id', models.CharField(max_length=50, null=True, unique=True)),
                ('game_name', models.CharField(max_length=100, null=True, verbose_name='Jokoa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streamingak', to=settings.AUTH_USER_MODEL, verbose_name='Erabiltzailea')),
            ],
            options={
                'verbose_name': 'Streaming',
                'verbose_name_plural': 'Streamingak',
            },
        ),
    ]
