dist: xenial
language: python

python:
  - "3.7"

services:
  - mysql

env:
  - DJANGO="Django>2.0.0"

install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0.0,<2.1.0"

  allow_failures:
    - python: "3.6"
