dist: xenial
language: python

python:
  - "3.6.12"

services:
  - mysql
  - docker

env:
  - DJANGO="Django>2.0.0"

install:
  - pip install pip==20.0.2
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls

deploy:
  provider: script
  script: bash ./ci/build_push_docker.sh
  on:
    branch: main
