language: python

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="Django>2.0.0"

install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls
