version: '2.1'

services:
  db:
   restart: unless-stopped
   environment:
     - MATOMO_DATABASE_DBNAME
     - MATOMO_DATABASE_USERNAME
     - MATOMO_DATABASE_PASSWORD
  web:
   image: gamerauntsia/web:latest
   restart: unless-stopped
  proxy:
   restart: unless-stopped
  https-portal:
    image: steveltn/https-portal:1
    restart: unless-stopped
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - proxy
    environment:
      - DOMAINS=www.gamerauntsia.eus => https://gamerauntsia.eus, gamerauntsia.eus -> http://proxy:80
      - STAGE=production
      - CLIENT_MAX_BODY_SIZE=10m
      - PROXY_BUFFERS=4 32k
      - PROXY_CONNECT_TIMEOUT=120
      - PROXY_SEND_TIMEOUT=120
      - PROXY_READ_TIMEOUT=120
    volumes:
      - ssl-certs:/var/lib/https-portal
  backup:
    build: backup
    depends_on:
      - db
    environment:
      - RESTIC_REPOSITORY
      - RESTIC_PASSWORD
      - RESTIC_FORGET_ARGS
      - BACKUP_CRON
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY
      - MYSQL_DATABASE
      - MYSQL_BACKUP_USER
      - MYSQL_BACKUP_USER_PASSWORD
    volumes:
      - mediafiles:/data/media/:ro
      - matomo-config:/data/matomo-config/:ro
      - ./backup/hooks:/hooks:ro
  matomo:
    image: matomo:4.4.1
    environment:
      - MATOMO_DATABASE_USERNAME
      - MATOMO_DATABASE_PASSWORD
      - MATOMO_DATABASE_DBNAME
      - MATOMO_DATABASE_HOST
    volumes:
      - matomo-config:/var/www/html/config
volumes:
  ssl-certs:
  matomo-config:
