# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-23 23:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0010_auto_20160105_1307'),
        ('jokoa', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partaidea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(blank=True, max_length=64, null=True)),
                ('irabazlea', models.BooleanField(default=False)),
                ('win', models.IntegerField(default=0, verbose_name=b'Irabazitakoak')),
                ('lose', models.IntegerField(default=0, verbose_name=b'Galdutakoak')),
                ('draw', models.IntegerField(default=0, verbose_name=b'Berdindutakoak')),
                ('matches', models.IntegerField(default=0, verbose_name=b'Jokatutakoak')),
                ('average', models.FloatField(default=0, verbose_name=b'Gorabeherakoa')),
                ('points', models.IntegerField(default=0, verbose_name=b'Puntuak')),
                ('irudia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
                ('jokalariak', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name=b'Titularrak')),
                ('kapitaina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kapitaina', to=settings.AUTH_USER_MODEL)),
                ('ordezkoak', models.ManyToManyField(blank=True, related_name='ordezkoak', to=settings.AUTH_USER_MODEL, verbose_name=b'Ordezkoak')),
            ],
            options={
                'verbose_name': 'Partaidea',
                'verbose_name_plural': 'Partaideak',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jardunaldia', models.IntegerField(default=1, verbose_name=b'Jardunaldia')),
                ('emaitza', models.CharField(blank=True, max_length=50, null=True)),
                ('average', models.CharField(blank=True, max_length=50, null=True)),
                ('is_return', models.BooleanField(default=False, verbose_name=b'Itzulerakoa')),
                ('is_playoff', models.BooleanField(default=False, help_text=b'Markatu hau txapelketa konbinatu bateko playoff-aren partida bat bada', verbose_name=b'Playoff motakoa')),
                ('bideoa', models.CharField(blank=True, max_length=150, null=True)),
                ('start', models.IntegerField(blank=True, null=True, verbose_name=b'Hasiera')),
                ('end', models.IntegerField(blank=True, null=True, verbose_name=b'Bukaera')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name=b'Data')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='txapelketak.Partida')),
                ('partaideak', models.ManyToManyField(blank=True, to='txapelketak.Partaidea')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidak',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Txapelketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=64)),
                ('slug', models.SlugField(help_text=b'Eremu honetan kategoria honen URL helbidea zehazten ari zara.', unique=True)),
                ('desk', models.TextField(blank=True, max_length=256, null=True)),
                ('arauak', models.TextField(blank=True, max_length=256, null=True)),
                ('saria', models.TextField(blank=True, max_length=256, null=True)),
                ('mota', models.CharField(choices=[(b'0', b'Kanporaketa'), (b'1', b'Liga'), (b'2', b'Konbinatua')], default=b'0', max_length=1)),
                ('modalitatea', models.CharField(choices=[(b'0', b'Bakarka'), (b'1', b'Taldeka')], default=b'0', max_length=1)),
                ('status', models.CharField(choices=[(b'0', b'Izen ematea zabalik'), (b'1', b'Partidak sortzen'), (b'2', b'Txapelketa jokuan'), (b'3', b'Bukatuta')], default=b'0', max_length=1)),
                ('live_bideoa', models.CharField(blank=True, help_text=b'Eremu honetan bideoaren URL kodea itsatsi behar duzu. Adb.: c21XAuI3aMo', max_length=100, null=True)),
                ('twitch', models.BooleanField(default=False)),
                ('hashtag', models.CharField(blank=True, max_length=100, null=True)),
                ('irabazi', models.IntegerField(default=0, verbose_name=b'Puntuak irabaztean')),
                ('galdu', models.IntegerField(default=0, verbose_name=b'Puntuak galtzean')),
                ('berdinketa', models.IntegerField(default=0, verbose_name=b'Puntuak berdinketan')),
                ('publikoa_da', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Publikazio data')),
                ('insk_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Izen ematea')),
                ('shared', models.BooleanField(default=False)),
                ('adminak', models.ManyToManyField(related_name='adminak', to=settings.AUTH_USER_MODEL, verbose_name=b'Egileak')),
                ('irudia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
                ('jokalariak', models.ManyToManyField(blank=True, related_name='jokalariak', to=settings.AUTH_USER_MODEL, verbose_name=b'Inskripzioa')),
                ('jokoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokoa.Jokoa')),
            ],
            options={
                'verbose_name': 'Txapelketa',
                'verbose_name_plural': 'Txapelketak',
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='txapelketa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='txapelketak.Txapelketa'),
        ),
        migrations.AddField(
            model_name='partaidea',
            name='txapelketa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='txapelketak.Txapelketa'),
        ),
    ]
