# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txapelketak', '0002_txapelketa_manual_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txapelketa',
            name='desk',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
