# Generated by Django 2.2.16 on 2020-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamer", "0003_auto_20190617_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jokuplataforma",
            name="plataforma",
            field=models.CharField(
                choices=[
                    ("steam", "Steam"),
                    ("origin", "Origin"),
                    ("epic", "Epic Games"),
                    ("lol", "League of Legends"),
                    ("uplay", "Uplay"),
                    ("xbox", "XBOX"),
                    ("ps4", "PS4"),
                    ("wii", "Wii"),
                    ("archeage", "Archeage"),
                    ("wow", "World of Warcraft"),
                    ("bnet", "Battlenet"),
                    ("minecraft", "Minecraft"),
                ],
                max_length=10,
            ),
        ),
    ]
