# Generated by Django 2.2.17 on 2020-12-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamer", "0011_auto_20201225_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameruser",
            name="channel_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Kanalaren deskribapen laburra"
            ),
        ),
    ]
