# Generated by Django 2.2.2 on 2019-06-17 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finished', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished', to=settings.AUTH_USER_MODEL),
        ),
    ]
