# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 07:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('photologue', '0010_auto_20160105_1307'),
        ('jokoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Izen osoa')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia/deskribapena')),
                ('usertype', models.PositiveSmallIntegerField(choices=[(0, b'Erabiltzailea'), (1, b'Kidea'), (2, b'Nor publikoa'), (3, b'Kazetaria'), (4, b'Administratzailea')], default=0)),
                ('added_source', models.PositiveSmallIntegerField(choices=[(0, b'-'), (1, b'Register'), (2, b'Twitter'), (3, b'Facebook'), (4, b'OpenId')], default=0)),
                ('twitter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('openid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('googleplus_id', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name=b'Telegram kodea')),
                ('is_gamer', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True, null=True, verbose_name=b'Foro sinadura')),
                ('devices', models.TextField(blank=True, null=True, verbose_name=b'Mugikor gailuaen IDak')),
                ('ytube_channel', models.CharField(blank=True, max_length=150, null=True)),
                ('twitch_channel', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Twitch kanala')),
                ('email_notification', models.BooleanField(default=True, verbose_name=b'Eztabaidak')),
                ('buletin_notification', models.BooleanField(default=True, verbose_name=b'Buletinak')),
                ('motherboard', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Txartel nagusia')),
                ('processor', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Prozesagailua')),
                ('graphics', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Txartel grafikoa')),
                ('soundcard', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Soinu txartela')),
                ('ram', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'RAM Memoria')),
                ('harddrive', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Disko gogorra')),
                ('harddrive2', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Bigarren disko gogorra')),
                ('mouse', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Sagua')),
                ('keyboard', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Teklatua')),
                ('speakers', models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Bozgorailuak')),
                ('karma', models.IntegerField(default=0, verbose_name=b'Karma')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
                ('top_jokoak', models.ManyToManyField(blank=True, to='jokoa.Jokoa')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'GE Erabiltzailea',
                'verbose_name_plural': 'GE Erabiltzaileak',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AmaitutakoJokoak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=150)),
                ('urtea', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'publikazio data')),
                ('mod_date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'modifikazio data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amaitutakoak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amaiatutakoak',
                'verbose_name_plural': 'Amaiatutakoak',
            },
        ),
        migrations.CreateModel(
            name='JokuPlataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[(b'steam', b'Steam'), (b'origin', b'Origin'), (b'lol', b'League of Legends'), (b'uplay', b'Uplay'), (b'xbox', b'XBOX'), (b'ps4', b'PS4'), (b'wii', b'Wii'), (b'archeage', b'Archeage'), (b'wow', b'World of Warcraft'), (b'bnet', b'Battlenet'), (b'minecraft', b'Minecraft')], max_length=10)),
                ('nick', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataforma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformak',
            },
        ),
    ]
