# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameruser',
            name='twitch_channel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Twitch kanala'),
        ),
    ]
