# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0002_gameruser_twitch_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameruser',
            name='devices',
            field=models.TextField(blank=True, null=True, verbose_name=b'Mugikor gailuaen IDak'),
        ),
    ]
