# Generated by Django 2.2.17 on 2020-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamer", "0004_auto_20201012_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameruser",
            name="mastodon_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
