# Generated by Django 2.2.17 on 2020-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0009_auto_20201225_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameruser',
            name='channel_description',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
    ]
