# Generated by Django 2.2.17 on 2021-04-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamer", "0012_auto_20201226_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameruser",
            name="peertube_channel",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Peertube kanala"
            ),
        ),
    ]
