# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jokoa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_eu", models.CharField(max_length=64)),
                ("term_es", models.CharField(blank=True, max_length=64, null=True)),
                ("term_en", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "jokoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jokoa.Jokoa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminoa",
                "verbose_name_plural": "Terminoak",
            },
        ),
    ]
