# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokoa', '0003_auto_20170606_1607'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminoa',
            name='jokoak',
            field=models.ManyToManyField(blank=True, to='jokoa.Jokoa'),
        ),
        migrations.AlterField(
            model_name='terminoa',
            name='jokoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jokoa', to='jokoa.Jokoa'),
        ),
        migrations.AlterField(
            model_name='terminoa',
            name='term_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminoa',
            name='term_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminoa',
            name='term_eu',
            field=models.TextField(),
        ),
    ]
