# Generated by Django 2.2.2 on 2019-06-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20171211_2352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminoa",
            name="jokoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jokoa",
                to="jokoa.Jokoa",
            ),
        ),
    ]
