# Generated by Django 2.2.28 on 2023-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('izena_ingelesez', models.CharField(max_length=256, verbose_name='Izena ingelesez')),
                ('izena_euskaraz', models.CharField(max_length=256, verbose_name='Izena euskaraz')),
                ('izena_euskaraz_azalpena', models.CharField(max_length=256, verbose_name='Euskarazko izenaren azalpen laburra')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemonak',
            },
        ),
    ]
