# Generated by Django 2.2.28 on 2023-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="deskribapena",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
