# Generated by Django 4.2.20 on 2025-05-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0002_pokemon_deskribapena"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonGeneration",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Belaunaldia",
                "verbose_name_plural": "Belaunaldiak",
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="pokemon_generation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pokedex.pokemongeneration",
                verbose_name="Belaunaldia",
            ),
        ),
    ]
