# Generated by Django 4.2.20 on 2026-04-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0003_pokemongeneration_pokemon_pokemon_generation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonResource",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "izena_ingelesez",
                    models.CharField(max_length=256, verbose_name="Izena ingelesez"),
                ),
                (
                    "izena_euskaraz",
                    models.CharField(max_length=256, verbose_name="Izena euskaraz"),
                ),
                (
                    "deskribapena",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gaitasuna",
                "verbose_name_plural": "Gaitasunak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonCharacter",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pertsonaia",
                "verbose_name_plural": "Pertsonaiak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonItem",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objektu",
                "verbose_name_plural": "Objektuak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonLocation",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tokia",
                "verbose_name_plural": "Tokiak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonMove",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erasoa",
                "verbose_name_plural": "Erasoak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonPokedex",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pokedexa",
                "verbose_name_plural": "Pokedexak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonRegion",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lurraldea",
                "verbose_name_plural": "Lurradeak",
            },
            bases=("pokedex.pokemonresource",),
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "pokemonresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pokedex.pokemonresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mota",
                "verbose_name_plural": "Motak",
            },
            bases=("pokedex.pokemonresource",),
        ),
    ]
