# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 18, 56, 52, 257768, tzinfo=utc)),
        ),
    ]
