# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 12:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0006_auto_20161104_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 12, 33, 17, 236298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bazkidea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bazkidea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='eskaintza',
            name='mota',
            field=models.IntegerField(choices=[(1, b'Eskatzekoa'), (2, b'Parte hartzekoa'), (3, b'Eskubidea')], default=1),
        ),
    ]
