# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0010_auto_20161105_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eskaera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Eskaera',
                'verbose_name_plural': 'Eskaerak',
            },
        ),
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 21, 20, 7, 729163, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eskaera',
            name='bazkidea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazkidetza.Bazkidea'),
        ),
        migrations.AddField(
            model_name='eskaera',
            name='eskaintza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazkidetza.Eskaintza'),
        ),
    ]
