# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jokoa", "0003_auto_20170606_1607"),
        ("jokoen_itzulpenak", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="euskarazkojokoa",
            name="plataforma",
        ),
        migrations.RemoveField(
            model_name="itzulpena",
            name="jokoa",
        ),
        migrations.RemoveField(
            model_name="itzulpena",
            name="plataforma",
        ),
        migrations.AddField(
            model_name="euskarazkojokoa",
            name="itzulpena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jokoen_itzulpenak.Itzulpena",
            ),
        ),
        migrations.AddField(
            model_name="itzulpena",
            name="instalazioa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="itzulpena",
            name="izena",
            field=models.CharField(max_length=150, verbose_name="Fitxategi izena"),
        ),
    ]
