# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokoen_itzulpenak', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retro_IPS',
            new_name='Itzulpena',
        ),
        migrations.AlterModelOptions(
            name='itzulpena',
            options={'verbose_name': 'Itzulpen fitxategia', 'verbose_name_plural': 'Itzulpen fitxategiak'},
        ),
    ]
