# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokoen_itzulpenak", "0004_auto_20170606_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="euskarazkojokoa",
            name="online_url",
            field=models.URLField(blank=True, verbose_name="Online itzulpen proiektua"),
        ),
    ]
