# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokoen_itzulpenak', '0005_euskarazkojokoa_online_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itzulpena',
            name='instalazioa',
        ),
        migrations.AddField(
            model_name='euskarazkojokoa',
            name='instalazioa',
            field=models.TextField(blank=True),
        ),
    ]
