# Generated by Django 2.2.2 on 2019-06-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jokoen_itzulpenak", "0006_auto_20171212_2257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="euskalinkak",
            name="irudia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photologue.Photo"
            ),
        ),
        migrations.AlterField(
            model_name="euskarazkojokoa",
            name="itzulpena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jokoen_itzulpenak.Itzulpena",
            ),
        ),
        migrations.AlterField(
            model_name="euskarazkojokoa",
            name="jokoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="jokoa.Jokoa"
            ),
        ),
        migrations.AlterField(
            model_name="itzulpena",
            name="status",
            field=models.CharField(
                choices=[
                    ("-", "Hasita"),
                    ("0", "Erdizka"),
                    ("1", "Probatzeko"),
                    ("2", "Amaituta"),
                ],
                default="0",
                max_length=1,
                verbose_name="Egoera",
            ),
        ),
    ]
