# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jokoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=64)),
                ('slug', models.SlugField(help_text=b'Eremu honetan joko honen URL helbidea zehazten ari zara.', unique=True)),
                ('desk', models.TextField(blank=True, max_length=256, null=True, verbose_name=b'Deskribapena')),
                ('bertsioa', models.CharField(blank=True, help_text=b'Joko saga bat bada, zehaztu hemen bertsioa.', max_length=64, null=True)),
                ('lizentzia', models.CharField(choices=[(b'C', b'Copyright'), (b'FR', b'Doakoa'), (b'OS', b'Kode Irekia')], default=b'C', max_length=2)),
                ('steam_id', models.IntegerField(blank=True, help_text=b'Jokoa Steam plataforman aurki badaiteke, jokoaren fitxaren URLan agertzen den zenbakia. Adibidez: 236110', null=True)),
                ('trailer', models.CharField(blank=True, help_text=b'Steam ID zenbakia jarrita badago, ez da beharrezkoa. Bestela, Youtube bideoaren KODEA itsatsi. Adibidez: bkgzXpKbVGE', max_length=64, null=True, verbose_name=b'Youtube trailerra')),
                ('url', models.CharField(help_text=b'Eremu honetan joko honen atariko URL helbidea zehazten ari zara.', max_length=64)),
                ('wiki', models.CharField(blank=True, help_text=b'Eremu honetan joko honen wikipediako URL helbidea zehaztu mesedez.', max_length=64, null=True)),
                ('publikoa_da', models.BooleanField(default=False)),
                ('logoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
            ],
            options={
                'verbose_name': 'Jokoa',
                'verbose_name_plural': 'Jokoak',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=64)),
                ('slug', models.SlugField(help_text=b'Eremu honetan plataforma honen URL helbidea zehazten ari zara.', unique=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformak',
            },
        ),
    ]
