# Generated by Django 2.2.26 on 2022-05-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photologue", "0011_auto_20190223_2138"),
        ("jokoa", "0004_auto_20190617_1316"),
    ]

    operations = [
        migrations.AddField(
            model_name="jokoa",
            name="argitaratze_data",
            field=models.DateField(
                blank=True,
                help_text="Jokoa noiz argitaratu zen edo argitaratuko den.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Garatzailea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("izena", models.CharField(max_length=64)),
                (
                    "desk",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Deskribapena",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("url", models.CharField(max_length=64)),
                ("sorrera_data", models.DateField(blank=True, null=True)),
                ("itxiera_data", models.DateField(blank=True, null=True)),
                (
                    "logoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photologue.Photo",
                    ),
                ),
                ("plataformak", models.ManyToManyField(to="jokoa.Plataforma")),
            ],
            options={
                "verbose_name": "Garatzailea",
                "verbose_name_plural": "Garatzaileak",
            },
        ),
        migrations.AddField(
            model_name="jokoa",
            name="garatzailea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jokoa.Garatzailea",
            ),
        ),
    ]
