# Generated by Django 2.2.28 on 2022-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokoa", "0007_auto_20220604_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jokoa",
            name="lizentzia",
            field=models.CharField(
                choices=[
                    ("C", "Jabeduna - ordainpekoa"),
                    ("FR", "Jabeduna - doakoa"),
                    ("OS", "Librea edo irekia"),
                ],
                default="C",
                max_length=2,
            ),
        ),
    ]
