# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("bazkidetza", "0002_auto_20170606_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bazkidea",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 6, 6, 16, 24, 15, 142499, tzinfo=utc)
            ),
        ),
    ]
