#!/bin/bash

set -eu -o pipefail
mysql -uroot -p${MYSQL_ROOT_PASSWORD} <<EOF
GRANT LOCK TABLES, SELECT ON ${MYSQL_DATABASE}.* TO ${MYSQL_BACKUP_USER}@'%' IDENTIFIED BY '${MYSQL_BACKUP_USER_PASSWORD}';
EOF
