# Generated by Django 2.2.26 on 2022-05-30 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jokoa", "0005_auto_20220530_1818"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JokoItzulpena",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sortze_data",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("erabilgarritasun_data", models.DateTimeField(blank=True, null=True)),
                (
                    "publikoa_da",
                    models.BooleanField(default=True, verbose_name="Publikoa da"),
                ),
                (
                    "ofiziala_da",
                    models.BooleanField(default=False, verbose_name="Ofiziala da"),
                ),
                (
                    "jatorria",
                    models.CharField(
                        choices=[
                            ("0", "Jatorrizkoa euskaraz"),
                            ("1", "Garatzaileen itzulpena"),
                            ("2", "Zaleen itzulpena"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "jokoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jokoa.Jokoa"
                    ),
                ),
                ("plataformak", models.ManyToManyField(to="jokoa.Plataforma")),
            ],
        ),
        migrations.CreateModel(
            name="ItzulpenProiektua",
            fields=[
                (
                    "jokoitzulpena_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="joko_itzulpenak.JokoItzulpena",
                    ),
                ),
                (
                    "egoera",
                    models.CharField(
                        choices=[
                            ("0", "Lanean"),
                            ("1", "Laguntza bila"),
                            ("2", "Bukatuta"),
                            ("3", "Eguneratzeke"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "deskribapena",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                ("url", models.CharField(blank=True, max_length=150, null=True)),
                ("instalazioa", models.TextField(blank=True, null=True)),
                ("ohar_teknikoak", models.TextField(blank=True, null=True)),
                (
                    "eguneratze_data",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "arduraduna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arduraduna",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Itzulpen proiektua",
                "verbose_name_plural": "Itzulpen proiektuak",
            },
            bases=("joko_itzulpenak.jokoitzulpena",),
        ),
        migrations.CreateModel(
            name="KanpokoItzulpena",
            fields=[
                (
                    "jokoitzulpena_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="joko_itzulpenak.JokoItzulpena",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "verbose_name": "Kanpoko itzulpena",
                "verbose_name_plural": "Kanpoko itzulpenak",
            },
            bases=("joko_itzulpenak.jokoitzulpena",),
        ),
        migrations.CreateModel(
            name="ItzulpenProiektuParteHartzailea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mota",
                    models.CharField(
                        choices=[
                            ("0", "Itzultzailea"),
                            ("1", "Zuzentzailea"),
                            ("2", "Laguntzailea"),
                            ("3", "Probatzailea"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "erabiltzailea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proiektua",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="joko_itzulpenak.ItzulpenProiektua",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proiektuko parte hartzailea",
                "verbose_name_plural": "Proiektuko parte hartzaileak",
            },
        ),
        migrations.AddField(
            model_name="itzulpenproiektua",
            name="parte_hartzaileak",
            field=models.ManyToManyField(
                through="joko_itzulpenak.ItzulpenProiektuParteHartzailea",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ItzulpenFitxategia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("izena", models.CharField(max_length=150)),
                (
                    "deskribapen_laburra",
                    models.CharField(
                        max_length=300, verbose_name="Deskribapen laburra"
                    ),
                ),
                (
                    "fitxategia",
                    models.FileField(
                        blank=True, null=True, upload_to="itzulpen_fitxategiak"
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "sortze_data",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "proiektua",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="joko_itzulpenak.ItzulpenProiektua",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itzulpen fitxategia",
                "verbose_name_plural": "Itzulpen fitxategiak",
            },
        ),
    ]
