# Generated by Django 2.2.26 on 2022-05-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joko_itzulpenak", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jokoitzulpena",
            name="erabilgarritasun_data",
            field=models.DateField(blank=True, null=True),
        ),
    ]
