# Generated by Django 2.2.26 on 2022-05-30 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("joko_itzulpenak", "0002_auto_20220530_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itzulpenproiektua",
            name="eguneratze_data",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="jokoitzulpena",
            name="sortze_data",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
