# Generated by Django 2.2.2 on 2019-06-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("photologue", "0010_auto_20160105_1307"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("izena", models.CharField(max_length=100)),
                (
                    "deskribapena",
                    models.TextField(
                        blank=True, null=True, verbose_name="Deskribapena"
                    ),
                ),
                ("telegram_kodea", models.CharField(max_length=100)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photologue.Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram taldea",
                "verbose_name_plural": "Telegram taldeak",
            },
        ),
    ]
