# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplaya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplaya',
            name='slug',
            field=models.SlugField(help_text=b'Eremu honetan game play honen URL helbidea zehazten ari zara.', max_length=200, unique=True),
        ),
    ]
