# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 15, 24, 11, 737338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='oparitzekojokoak',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'publikazio data'),
        ),
    ]
