# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0004_auto_20161104_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskaintza',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 20, 34, 10, 605272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eskaintza',
            name='mota',
            field=models.IntegerField(choices=[(1, b'Eskatzekoa'), (2, b'Parte hartzekoa')], default=1),
        ),
    ]
