# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0005_auto_20161104_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskaintza',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 21, 30, 20, 454752, tzinfo=utc)),
        ),
    ]
