# Generated by Django 2.2.26 on 2022-02-16 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0006_auto_20190617_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 18, 14, 28, 201113, tzinfo=utc)),
        ),
    ]
