# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0007_auto_20161105_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 12, 50, 24, 812073, tzinfo=utc)),
        ),
    ]
