# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0009_auto_20161105_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='oparitzekojokoak',
            name='non_aldatzeko',
            field=models.IntegerField(choices=[(1, b'Steam'), (2, b'Origin')], default=1),
        ),
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 18, 1, 39, 239310, tzinfo=utc)),
        ),
    ]
