# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0011_auto_20161215_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 20, 53, 39, 55000, tzinfo=utc)),
        ),
    ]
