# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-23 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0012_auto_20161218_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 23, 28, 38, 583881, tzinfo=utc)),
        ),
    ]
