# Generated by Django 2.2.28 on 2022-07-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazkidetza', '0015_auto_20220217_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazkidea',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
