# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasting', '0004_auto_20160822_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, help_text="\n            This is your chance to tell potential subscribers all about your podcast.\n            Describe your subject matter, media format, episode schedule, and other\n            relevant info so that they know what they'll be getting when they\n            subscribe. In addition, make a list of the most relevant search terms\n            that you want your podcast to match, then build them into your\n            description. Note that iTunes removes podcasts that include lists of\n            irrelevant words in the itunes:summary, description, or\n            itunes:keywords tags. This field can be up to 4000 plain text characters.\n            No HTML tags or styling allowed.", max_length=4000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='show',
            name='license',
            field=models.CharField(help_text='To publish a podcast to iTunes it is required to set a license type.', max_length=255, verbose_name='license'),
        ),
    ]
