# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 07:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aurkezpena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=64)),
                ('slug', models.SlugField(help_text='Eremu honetan aurkezpen honen URL helbidea zehazten ari zara.', unique=True)),
                ('abstract', models.TextField(blank=True, max_length=256, null=True)),
                ('slides', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='publikazio data')),
                ('mod_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='modifikazio data')),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aurkezpenak',
                'verbose_name_plural': 'Aurkezpena',
            },
        ),
    ]
