# Generated by Django 2.2.28 on 2022-06-04 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photologue", "0011_auto_20190223_2138"),
        ("base", "0003_auto_20190617_1316"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProiektuLaguna",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("izena", models.CharField(max_length=150, verbose_name="Izena")),
                ("url", models.URLField()),
                (
                    "publikoa_da",
                    models.BooleanField(default=False, verbose_name="Publikoa da"),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="publikazio data"
                    ),
                ),
                (
                    "irudia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photologue.Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proiektu laguna",
                "verbose_name_plural": "Proiektu lagunak",
            },
        ),
    ]
