# Generated by Django 2.2.28 on 2023-10-01 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("photologue", "0011_auto_20190223_2138"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastShow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Planned"), ("1", "Ongoing"), ("2", "Legacy")],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="photologue.Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcasta",
                "verbose_name_plural": "Podcastak",
            },
        ),
        migrations.CreateModel(
            name="PodcastSeason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("number", models.IntegerField(default=0)),
                (
                    "podcast_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="podcast.PodcastShow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denboraldia",
                "verbose_name_plural": "Denboraldiak",
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("number", models.IntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="photologue.Photo",
                    ),
                ),
                (
                    "podcast_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="podcast.PodcastSeason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saioa",
                "verbose_name_plural": "Saioak",
            },
        ),
    ]
