# Generated by Django 2.2.28 on 2023-10-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastAudioPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("priority", models.IntegerField(default=0)),
                (
                    "link_url_pattern",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "Podcast audio paltaforma",
                "verbose_name_plural": "Podcast audio plataformak",
            },
        ),
        migrations.CreateModel(
            name="PodcastVideoPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("priority", models.IntegerField(default=0)),
                (
                    "embed_url_pattern",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "link_url_pattern",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "Podcast bideo plataforma",
                "verbose_name_plural": "Podcast bideo plataformak",
            },
        ),
        migrations.AlterField(
            model_name="podcastseason",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PodcastEpisodeVideoPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(max_length=100, verbose_name="Bideoaren kodea"),
                ),
                (
                    "podcast_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.PodcastEpisode",
                    ),
                ),
                (
                    "video_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.PodcastVideoPlatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saioaren bideoa",
                "verbose_name_plural": "Saioaren bideoak",
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeAudioPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_id",
                    models.CharField(max_length=100, verbose_name="Audioaren kodea"),
                ),
                (
                    "override_link_url",
                    models.CharField(max_length=250, verbose_name="Audioaren URLa"),
                ),
                (
                    "audio_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.PodcastAudioPlatform",
                    ),
                ),
                (
                    "podcast_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.PodcastEpisode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saioaren audioa",
                "verbose_name_plural": "Saioaren audioak",
            },
        ),
    ]
