# Generated by Django 2.2.28 on 2023-10-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0002_auto_20231012_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisodeaudioplatform",
            name="audio_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Audioaren kodea"
            ),
        ),
        migrations.AlterField(
            model_name="podcastepisodeaudioplatform",
            name="override_link_url",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Audioaren URLa"
            ),
        ),
    ]
