name: CI/CD

on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{vars.IMAGE_NAME}}
      REGISTRY_ADDRESS: ${{vars.REGISTRY_ADDRESS}}
      REGISTRY_URL: ${{vars.REGISTRY_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      DJANGO: "Django>2.0.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Black check
        run: |
          pip install black
          black --check gamerauntsia

      - name: Build and publish Docker image
        run: ./ci/build_push_docker.sh
