name: CI/CD

on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{vars.DOCKER_IMAGE_NAME}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Download latest Docker image for caching
        run: docker pull ${DOCKER_IMAGE_NAME}

      - name: Build dev/ci Docker image
        run: |
          docker build \
          --target development \
          --cache-from ${DOCKER_IMAGE_NAME} .

      - name: Start environment
        run: docker-compose up -d

      - name: Run black check
        run: docker-compose exec -T --user gamerauntsia web python -m black --check .

      - name: Stop environment
        run: docker-compose down -t0

      - name: Build production Docker image
        run: |
          docker build \
          --tag ${DOCKER_IMAGE_NAME}:latest \
          --target production .

      - name: Publish production latest Docker image
        run: docker push ${DOCKER_IMAGE_NAME}:latest

      - name: Publish production versioned Docker image
        run: |
          VERSION=$(date '+%Y-%m-%d__%H-%M-%S')
          VERSIONED_NAME=${DOCKER_IMAGE_NAME}:${VERSION}
          docker tag ${DOCKER_IMAGE_NAME}:latest ${VERSIONED_NAME}
          docker push ${VERSIONED_NAME}
