name: CI/CD

on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{vars.IMAGE_NAME}}
      REGISTRY_ADDRESS: ${{vars.REGISTRY_ADDRESS}}
      REGISTRY_URL: ${{vars.REGISTRY_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start environment
        run: |
          docker-compose up -d

      - name: Run black check
        run: |
          docker-compose exec -T --user gamerauntsia web python -m black --check .

      - name: Build and publish Docker image
        run: ./ci/build_push_docker.sh
