# Generated by Django 2.2.2 on 2019-06-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("getb", "0002_auto_20170606_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atala",
            name="argazkia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="photologue.Photo"
            ),
        ),
    ]
